### ISSUE TITLE
About the FRICP result with your dataset

### ISSUE THREAD

**Issue by murphylmf** [HengyiWang/MorpheuS#1]
Hi Hengyi,

Thank you for your great work! 

I'm trying to use MorpheuS in my project, but when I tried to use my custom data according to your preprocessing pipeline, I found that FRICP always failed. So I tried to use your provided dataset (e.g. ddeform_seq002 and snoopy) to test the FRICP, but also fails. The results seem like this.
![seq002](https://github.com/user-attachments/assets/3fb7143c-f8ba-44d8-b908-e9b4fdd7cf20)
![snoopy](https://github.com/user-attachments/assets/1720a2de-89b5-4b3c-a8d3-5e1b4e2af200)

Do you have any ideas or suggestions?

**Comment by HengyiWang** [comment]
Hi @murphylmf, thanks for using our code. Can you double-check your depth scale (1000), mask file, and intrinsic? Also, make sure you are using the raw images & intrinsics for preprocessing. Feel free to reach out if the problem persists:)

**Comment by HengyiWang** [comment]
Hi @murphylmf, I have included the intrinsic.txt in the test scene, now you can directly run

`python step1.py --depth_scale 1000. --data_path ../data/kfusion_snoopy/ --registration_alg_path './Fast-Robust-ICP/build/FRICP'`

**Comment by murphylmf** [comment]
> Hi @murphylmf, I have included the intrinsic.txt in the test scene, now you can directly run
> 
> `python step1.py --depth_scale 1000. --data_path ../data/kfusion_snoopy/ --registration_alg_path './Fast-Robust-ICP/build/FRICP'`

I update the kfusion_snoopy folder and directly run this command, but the FRICP still failed.

![snoopy_2](https://github.com/user-attachments/assets/8e1fdfb7-606a-4443-96a4-a6bced84c3c8)\]

**Comment by HengyiWang** [comment]
> I update the kfusion_snoopy folder and directly run this command, but the FRICP still failed.

Hi @murphylmf, I have checked with the pipeline, and I think your result might actually be correct, the object should be within that unit sphere, you can remove it from meshlab. I have tested the code again, the correct results should look like this: 
<img width="912" alt="snoopy1" src="https://github.com/user-attachments/assets/021633ed-2827-4f20-b455-c5ef1b5ef8dd">
<img width="548" alt="snoopy2" src="https://github.com/user-attachments/assets/015d828d-8164-4c3c-b4df-83ffe9a0cd1a">

**Comment by murphylmf** [comment]
Yeah, thank you, I can now pruduce the correct result. I'm now trying to process my own dataset. I'll close this issue.

Thanks a lot for your assistance!
